// Code generated by MockGen. DO NOT EDIT.
// Source: vendor/github.com/teamwork/datadog/v2/client.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	v2 "github.com/teamwork/datadog/v2"
)

// MockstatsdClient is a mock of statsdClient interface.
type MockstatsdClient struct {
	ctrl     *gomock.Controller
	recorder *MockstatsdClientMockRecorder
}

// MockstatsdClientMockRecorder is the mock recorder for MockstatsdClient.
type MockstatsdClientMockRecorder struct {
	mock *MockstatsdClient
}

// NewMockstatsdClient creates a new mock instance.
func NewMockstatsdClient(ctrl *gomock.Controller) *MockstatsdClient {
	mock := &MockstatsdClient{ctrl: ctrl}
	mock.recorder = &MockstatsdClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockstatsdClient) EXPECT() *MockstatsdClientMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockstatsdClient) Count(arg0 string, arg1 int64, arg2 []string, arg3 float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Count indicates an expected call of Count.
func (mr *MockstatsdClientMockRecorder) Count(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockstatsdClient)(nil).Count), arg0, arg1, arg2, arg3)
}

// Decr mocks base method.
func (m *MockstatsdClient) Decr(arg0 string, arg1 []string, arg2 float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decr", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Decr indicates an expected call of Decr.
func (mr *MockstatsdClientMockRecorder) Decr(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decr", reflect.TypeOf((*MockstatsdClient)(nil).Decr), arg0, arg1, arg2)
}

// Distribution mocks base method.
func (m *MockstatsdClient) Distribution(arg0 string, arg1 float64, arg2 []string, arg3 float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Distribution", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Distribution indicates an expected call of Distribution.
func (mr *MockstatsdClientMockRecorder) Distribution(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Distribution", reflect.TypeOf((*MockstatsdClient)(nil).Distribution), arg0, arg1, arg2, arg3)
}

// Gauge mocks base method.
func (m *MockstatsdClient) Gauge(arg0 string, arg1 float64, arg2 []string, arg3 float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Gauge", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Gauge indicates an expected call of Gauge.
func (mr *MockstatsdClientMockRecorder) Gauge(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Gauge", reflect.TypeOf((*MockstatsdClient)(nil).Gauge), arg0, arg1, arg2, arg3)
}

// Histogram mocks base method.
func (m *MockstatsdClient) Histogram(arg0 string, arg1 float64, arg2 []string, arg3 float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Histogram", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// Histogram indicates an expected call of Histogram.
func (mr *MockstatsdClientMockRecorder) Histogram(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Histogram", reflect.TypeOf((*MockstatsdClient)(nil).Histogram), arg0, arg1, arg2, arg3)
}

// Incr mocks base method.
func (m *MockstatsdClient) Incr(arg0 string, arg1 []string, arg2 float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Incr", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Incr indicates an expected call of Incr.
func (mr *MockstatsdClientMockRecorder) Incr(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Incr", reflect.TypeOf((*MockstatsdClient)(nil).Incr), arg0, arg1, arg2)
}

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockClient) Count(metric string, count int64, tags []string, options ...v2.ClientOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{metric, count, tags}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Count", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Count indicates an expected call of Count.
func (mr *MockClientMockRecorder) Count(metric, count, tags interface{}, options ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{metric, count, tags}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockClient)(nil).Count), varargs...)
}

// Decr mocks base method.
func (m *MockClient) Decr(metric string, tags []string, options ...v2.ClientOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{metric, tags}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Decr", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Decr indicates an expected call of Decr.
func (mr *MockClientMockRecorder) Decr(metric, tags interface{}, options ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{metric, tags}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decr", reflect.TypeOf((*MockClient)(nil).Decr), varargs...)
}

// Distribution mocks base method.
func (m *MockClient) Distribution(metric string, value float64, tags []string, options ...v2.ClientOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{metric, value, tags}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Distribution", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Distribution indicates an expected call of Distribution.
func (mr *MockClientMockRecorder) Distribution(metric, value, tags interface{}, options ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{metric, value, tags}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Distribution", reflect.TypeOf((*MockClient)(nil).Distribution), varargs...)
}

// Gauge mocks base method.
func (m *MockClient) Gauge(metric string, value float64, tags []string, options ...v2.ClientOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{metric, value, tags}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Gauge", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Gauge indicates an expected call of Gauge.
func (mr *MockClientMockRecorder) Gauge(metric, value, tags interface{}, options ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{metric, value, tags}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Gauge", reflect.TypeOf((*MockClient)(nil).Gauge), varargs...)
}

// Histogram mocks base method.
func (m *MockClient) Histogram(metric string, duration time.Duration, tags []string, options ...v2.ClientOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{metric, duration, tags}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Histogram", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Histogram indicates an expected call of Histogram.
func (mr *MockClientMockRecorder) Histogram(metric, duration, tags interface{}, options ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{metric, duration, tags}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Histogram", reflect.TypeOf((*MockClient)(nil).Histogram), varargs...)
}

// Incr mocks base method.
func (m *MockClient) Incr(metric string, tags []string, options ...v2.ClientOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{metric, tags}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Incr", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Incr indicates an expected call of Incr.
func (mr *MockClientMockRecorder) Incr(metric, tags interface{}, options ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{metric, tags}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Incr", reflect.TypeOf((*MockClient)(nil).Incr), varargs...)
}

// Namespace mocks base method.
func (m *MockClient) Namespace(namespace string, tags []string) v2.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Namespace", namespace, tags)
	ret0, _ := ret[0].(v2.Client)
	return ret0
}

// Namespace indicates an expected call of Namespace.
func (mr *MockClientMockRecorder) Namespace(namespace, tags interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Namespace", reflect.TypeOf((*MockClient)(nil).Namespace), namespace, tags)
}
